<?php

namespace FormationBundle\Repository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{

	public function compterNombreSession(){
		return $this->createQueryBuilder('f')
		->select('f.id,f.intitule,f.description,f.intitule, count(s.formation) as nombre')
		->leftJoin('FormationBundle\Entity\Session', 's' , 'WITH' , 's.formation = f.id')  
		->groupBy('f.intitule')
		->getQuery()
		->getResult();

	}
}
