<?php

namespace FormationBundle\Repository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
	public function compterNombreCandidat(){
		return $this->createQueryBuilder('s')
		->select('s.id, s.dateFin,s.dateDebut, count( p.sessions ) as nombre')
		->join('s.personnes', 'p') 
		->groupBy('s.id')
		->getQuery()
		->getResult();

	}

	public function listerSessionByIntitule($nom){
		return $this->createQueryBuilder('s')
		->select('s')
		->join('s.formation', 'f') 
		->andWhere('f.intitule = :nom')
		->setParameter('nom' , $nom)
		->getQuery()
		->getResult();

	}
}
