<?php

namespace PersonneBundle\Repository;

/**
 * MemoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByContenu($recherche){
		return $this->createQueryBuilder('m')
		->select('m')
		->where('m.contenu LIKE :recherche')
		->setParameter('recherche', $recherche['recherche'])
		->getQuery()
		->getResult();

	}

	public function paginationMemos($page){
		return $this->createQueryBuilder('m')
		->select('m')
		->setMaxResults(5)
        ->setFirstResult($page)
        ->orderBy('m.id', 'DESC')
		->getQuery()
		->getResult();

	}

	public function paginationMemosvPersonne($page,$personne){
		return $this->createQueryBuilder('m')
		->select('m')
		->andWhere('m.personne = :personne')
		->setParameter('personne' , $personne)
		->setMaxResults(5)
        ->setFirstResult($page)
		->getQuery()
		->getResult();

	}
}
