<?php

namespace PersonneBundle\Repository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends \Doctrine\ORM\EntityRepository
{
	public function findSortedByName(){
		return $this->createQueryBuilder('p')
		->select('p')
		->orderBy('p.nom', 'ASC')
		->getQuery()
		->getResult();


	}

	public function findByChoixNameOuPrenom($recherche){
		return $this->createQueryBuilder('p')
		->select('p')
		->where('p.nom LIKE :recherche')
		->orWhere('p.prenom LIKE :recherche')
		->setParameter('recherche', $recherche['recherche'])
		->getQuery()
		->getResult();

	}
}
